# Generated by Django 3.1.2 on 2021-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0003_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(related_name='tag', to='Userdetail.Publication'),
        ),
    ]
