# Generated by Django 3.1.2 on 2021-02-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdetail', '0004_auto_20210210_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='Userdetail.Publication'),
        ),
    ]
