# Generated by Django 3.1.2 on 2021-02-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userdetail', '0005_auto_20210211_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(related_name='tag', to='Userdetail.Publication'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tag', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
